// Custom options for protoc-gen-jsonschema
// Allocated range is 1125-1129
// See https://github.com/protocolbuffers/protobuf/blob/master/docs/options.md

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: options.proto

package protoc_gen_jsonschema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Custom FieldOptions
type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fields tagged with this will be omitted from generated schemas
	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Fields tagged with this will be marked as "required" in generated schemas
	Required bool `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	// Fields tagged with this will constrain strings using the "minLength" keyword in generated schemas
	MinLength int32 `protobuf:"varint,3,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	// Fields tagged with this will constrain strings using the "maxLength" keyword in generated schemas
	MaxLength int32 `protobuf:"varint,4,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	// Fields tagged with this will constrain strings using the "pattern" keyword in generated schemas
	Pattern string `protobuf:"bytes,5,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// Fields tagged with this will constrain numbers using the "minimum" keyword in generated schemas (inclusive lower bound)
	Minimum *float64 `protobuf:"fixed64,6,opt,name=minimum,proto3,oneof" json:"minimum,omitempty"`
	// Fields tagged with this will constrain numbers using the "maximum" keyword in generated schemas (inclusive upper bound)
	Maximum *float64 `protobuf:"fixed64,7,opt,name=maximum,proto3,oneof" json:"maximum,omitempty"`
	// Fields tagged with this will constrain numbers using the "exclusiveMinimum" keyword in generated schemas (exclusive lower bound)
	ExclusiveMinimum *float64 `protobuf:"fixed64,8,opt,name=exclusive_minimum,json=exclusiveMinimum,proto3,oneof" json:"exclusive_minimum,omitempty"`
	// Fields tagged with this will constrain numbers using the "exclusiveMaximum" keyword in generated schemas (exclusive upper bound)
	ExclusiveMaximum *float64 `protobuf:"fixed64,9,opt,name=exclusive_maximum,json=exclusiveMaximum,proto3,oneof" json:"exclusive_maximum,omitempty"`
	// Fields tagged with this will be constrained to a constant value in generated schemas (parsed based on field type)
	Const         string `protobuf:"bytes,10,opt,name=const,proto3" json:"const,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_options_proto_rawDescGZIP(), []int{0}
}

func (x *FieldOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

func (x *FieldOptions) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldOptions) GetMinLength() int32 {
	if x != nil {
		return x.MinLength
	}
	return 0
}

func (x *FieldOptions) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *FieldOptions) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *FieldOptions) GetMinimum() float64 {
	if x != nil && x.Minimum != nil {
		return *x.Minimum
	}
	return 0
}

func (x *FieldOptions) GetMaximum() float64 {
	if x != nil && x.Maximum != nil {
		return *x.Maximum
	}
	return 0
}

func (x *FieldOptions) GetExclusiveMinimum() float64 {
	if x != nil && x.ExclusiveMinimum != nil {
		return *x.ExclusiveMinimum
	}
	return 0
}

func (x *FieldOptions) GetExclusiveMaximum() float64 {
	if x != nil && x.ExclusiveMaximum != nil {
		return *x.ExclusiveMaximum
	}
	return 0
}

func (x *FieldOptions) GetConst() string {
	if x != nil {
		return x.Const
	}
	return ""
}

// Custom FileOptions
type FileOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Files tagged with this will not be processed
	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Override the default file extension for schemas generated from this file
	Extension     string `protobuf:"bytes,2,opt,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_options_proto_rawDescGZIP(), []int{1}
}

func (x *FileOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

func (x *FileOptions) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

// Custom MessageOptions
type MessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Messages tagged with this will not be processed
	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Messages tagged with this will have all fields marked as "required":
	AllFieldsRequired bool `protobuf:"varint,2,opt,name=all_fields_required,json=allFieldsRequired,proto3" json:"all_fields_required,omitempty"`
	// Messages tagged with this will additionally accept null values for all properties:
	AllowNullValues bool `protobuf:"varint,3,opt,name=allow_null_values,json=allowNullValues,proto3" json:"allow_null_values,omitempty"`
	// Messages tagged with this will have all fields marked as not allowing additional properties:
	DisallowAdditionalProperties bool `protobuf:"varint,4,opt,name=disallow_additional_properties,json=disallowAdditionalProperties,proto3" json:"disallow_additional_properties,omitempty"`
	// Messages tagged with this will have all nested enums encoded to use constants instead of simple types (supports value annotations):
	EnumsAsConstants bool `protobuf:"varint,5,opt,name=enums_as_constants,json=enumsAsConstants,proto3" json:"enums_as_constants,omitempty"`
	// Messages tagged with this will have their oneof fields converted into JSON Schema composition (valid values: "oneOf")
	OneofConvertInto string `protobuf:"bytes,6,opt,name=oneof_convert_into,json=oneofConvertInto,proto3" json:"oneof_convert_into,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_options_proto_rawDescGZIP(), []int{2}
}

func (x *MessageOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

func (x *MessageOptions) GetAllFieldsRequired() bool {
	if x != nil {
		return x.AllFieldsRequired
	}
	return false
}

func (x *MessageOptions) GetAllowNullValues() bool {
	if x != nil {
		return x.AllowNullValues
	}
	return false
}

func (x *MessageOptions) GetDisallowAdditionalProperties() bool {
	if x != nil {
		return x.DisallowAdditionalProperties
	}
	return false
}

func (x *MessageOptions) GetEnumsAsConstants() bool {
	if x != nil {
		return x.EnumsAsConstants
	}
	return false
}

func (x *MessageOptions) GetOneofConvertInto() string {
	if x != nil {
		return x.OneofConvertInto
	}
	return ""
}

// Custom EnumOptions
type EnumOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enums tagged with this will have be encoded to use constants instead of simple types (supports value annotations):
	EnumsAsConstants bool `protobuf:"varint,1,opt,name=enums_as_constants,json=enumsAsConstants,proto3" json:"enums_as_constants,omitempty"`
	// Enums tagged with this will only provide string values as options (not their numerical equivalents):
	EnumsAsStringsOnly bool `protobuf:"varint,2,opt,name=enums_as_strings_only,json=enumsAsStringsOnly,proto3" json:"enums_as_strings_only,omitempty"`
	// Enums tagged with this will have enum name prefix removed from values:
	EnumsTrimPrefix bool `protobuf:"varint,3,opt,name=enums_trim_prefix,json=enumsTrimPrefix,proto3" json:"enums_trim_prefix,omitempty"`
	// Enums tagged with this will not be processed
	Ignore bool `protobuf:"varint,4,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Enums tagged with this will have values converted to CamelCase format (after trim_prefix if enabled)
	EnumsAsCamelCase bool `protobuf:"varint,5,opt,name=enums_as_camel_case,json=enumsAsCamelCase,proto3" json:"enums_as_camel_case,omitempty"`
	// Enums tagged with this will have values converted to lowercase snake_case format (after trim_prefix if enabled)
	EnumsAsSnakeCase bool `protobuf:"varint,6,opt,name=enums_as_snake_case,json=enumsAsSnakeCase,proto3" json:"enums_as_snake_case,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnumOptions) Reset() {
	*x = EnumOptions{}
	mi := &file_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOptions) ProtoMessage() {}

func (x *EnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOptions.ProtoReflect.Descriptor instead.
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return file_options_proto_rawDescGZIP(), []int{3}
}

func (x *EnumOptions) GetEnumsAsConstants() bool {
	if x != nil {
		return x.EnumsAsConstants
	}
	return false
}

func (x *EnumOptions) GetEnumsAsStringsOnly() bool {
	if x != nil {
		return x.EnumsAsStringsOnly
	}
	return false
}

func (x *EnumOptions) GetEnumsTrimPrefix() bool {
	if x != nil {
		return x.EnumsTrimPrefix
	}
	return false
}

func (x *EnumOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

func (x *EnumOptions) GetEnumsAsCamelCase() bool {
	if x != nil {
		return x.EnumsAsCamelCase
	}
	return false
}

func (x *EnumOptions) GetEnumsAsSnakeCase() bool {
	if x != nil {
		return x.EnumsAsSnakeCase
	}
	return false
}

// Custom EnumValueOptions
type EnumValueOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enum values tagged with this will use a custom const value in generated schemas
	Const         string `protobuf:"bytes,1,opt,name=const,proto3" json:"const,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValueOptions) Reset() {
	*x = EnumValueOptions{}
	mi := &file_options_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueOptions) ProtoMessage() {}

func (x *EnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValueOptions.ProtoReflect.Descriptor instead.
func (*EnumValueOptions) Descriptor() ([]byte, []int) {
	return file_options_proto_rawDescGZIP(), []int{4}
}

func (x *EnumValueOptions) GetConst() string {
	if x != nil {
		return x.Const
	}
	return ""
}

var file_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         1125,
		Name:          "protoc.gen.jsonschema.field_options",
		Tag:           "bytes,1125,opt,name=field_options",
		Filename:      "options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         1126,
		Name:          "protoc.gen.jsonschema.file_options",
		Tag:           "bytes,1126,opt,name=file_options",
		Filename:      "options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         1127,
		Name:          "protoc.gen.jsonschema.message_options",
		Tag:           "bytes,1127,opt,name=message_options",
		Filename:      "options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*EnumOptions)(nil),
		Field:         1128,
		Name:          "protoc.gen.jsonschema.enum_options",
		Tag:           "bytes,1128,opt,name=enum_options",
		Filename:      "options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueOptions)(nil),
		Field:         1129,
		Name:          "protoc.gen.jsonschema.enum_value_options",
		Tag:           "bytes,1129,opt,name=enum_value_options",
		Filename:      "options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional protoc.gen.jsonschema.FieldOptions field_options = 1125;
	E_FieldOptions = &file_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional protoc.gen.jsonschema.FileOptions file_options = 1126;
	E_FileOptions = &file_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional protoc.gen.jsonschema.MessageOptions message_options = 1127;
	E_MessageOptions = &file_options_proto_extTypes[2]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional protoc.gen.jsonschema.EnumOptions enum_options = 1128;
	E_EnumOptions = &file_options_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional protoc.gen.jsonschema.EnumValueOptions enum_value_options = 1129;
	E_EnumValueOptions = &file_options_proto_extTypes[4]
)

var File_options_proto protoreflect.FileDescriptor

const file_options_proto_rawDesc = "" +
	"\n" +
	"\roptions.proto\x12\x15protoc.gen.jsonschema\x1a google/protobuf/descriptor.proto\"\x96\x03\n" +
	"\fFieldOptions\x12\x16\n" +
	"\x06ignore\x18\x01 \x01(\bR\x06ignore\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12\x1d\n" +
	"\n" +
	"min_length\x18\x03 \x01(\x05R\tminLength\x12\x1d\n" +
	"\n" +
	"max_length\x18\x04 \x01(\x05R\tmaxLength\x12\x18\n" +
	"\apattern\x18\x05 \x01(\tR\apattern\x12\x1d\n" +
	"\aminimum\x18\x06 \x01(\x01H\x00R\aminimum\x88\x01\x01\x12\x1d\n" +
	"\amaximum\x18\a \x01(\x01H\x01R\amaximum\x88\x01\x01\x120\n" +
	"\x11exclusive_minimum\x18\b \x01(\x01H\x02R\x10exclusiveMinimum\x88\x01\x01\x120\n" +
	"\x11exclusive_maximum\x18\t \x01(\x01H\x03R\x10exclusiveMaximum\x88\x01\x01\x12\x14\n" +
	"\x05const\x18\n" +
	" \x01(\tR\x05constB\n" +
	"\n" +
	"\b_minimumB\n" +
	"\n" +
	"\b_maximumB\x14\n" +
	"\x12_exclusive_minimumB\x14\n" +
	"\x12_exclusive_maximum\"C\n" +
	"\vFileOptions\x12\x16\n" +
	"\x06ignore\x18\x01 \x01(\bR\x06ignore\x12\x1c\n" +
	"\textension\x18\x02 \x01(\tR\textension\"\xa6\x02\n" +
	"\x0eMessageOptions\x12\x16\n" +
	"\x06ignore\x18\x01 \x01(\bR\x06ignore\x12.\n" +
	"\x13all_fields_required\x18\x02 \x01(\bR\x11allFieldsRequired\x12*\n" +
	"\x11allow_null_values\x18\x03 \x01(\bR\x0fallowNullValues\x12D\n" +
	"\x1edisallow_additional_properties\x18\x04 \x01(\bR\x1cdisallowAdditionalProperties\x12,\n" +
	"\x12enums_as_constants\x18\x05 \x01(\bR\x10enumsAsConstants\x12,\n" +
	"\x12oneof_convert_into\x18\x06 \x01(\tR\x10oneofConvertInto\"\x90\x02\n" +
	"\vEnumOptions\x12,\n" +
	"\x12enums_as_constants\x18\x01 \x01(\bR\x10enumsAsConstants\x121\n" +
	"\x15enums_as_strings_only\x18\x02 \x01(\bR\x12enumsAsStringsOnly\x12*\n" +
	"\x11enums_trim_prefix\x18\x03 \x01(\bR\x0fenumsTrimPrefix\x12\x16\n" +
	"\x06ignore\x18\x04 \x01(\bR\x06ignore\x12-\n" +
	"\x13enums_as_camel_case\x18\x05 \x01(\bR\x10enumsAsCamelCase\x12-\n" +
	"\x13enums_as_snake_case\x18\x06 \x01(\bR\x10enumsAsSnakeCase\"(\n" +
	"\x10EnumValueOptions\x12\x14\n" +
	"\x05const\x18\x01 \x01(\tR\x05const:h\n" +
	"\rfield_options\x12\x1d.google.protobuf.FieldOptions\x18\xe5\b \x01(\v2#.protoc.gen.jsonschema.FieldOptionsR\ffieldOptions:d\n" +
	"\ffile_options\x12\x1c.google.protobuf.FileOptions\x18\xe6\b \x01(\v2\".protoc.gen.jsonschema.FileOptionsR\vfileOptions:p\n" +
	"\x0fmessage_options\x12\x1f.google.protobuf.MessageOptions\x18\xe7\b \x01(\v2%.protoc.gen.jsonschema.MessageOptionsR\x0emessageOptions:d\n" +
	"\fenum_options\x12\x1c.google.protobuf.EnumOptions\x18\xe8\b \x01(\v2\".protoc.gen.jsonschema.EnumOptionsR\venumOptions:y\n" +
	"\x12enum_value_options\x12!.google.protobuf.EnumValueOptions\x18\xe9\b \x01(\v2'.protoc.gen.jsonschema.EnumValueOptionsR\x10enumValueOptionsB*Z(github.com/zbiljic/protoc-gen-jsonschemab\x06proto3"

var (
	file_options_proto_rawDescOnce sync.Once
	file_options_proto_rawDescData []byte
)

func file_options_proto_rawDescGZIP() []byte {
	file_options_proto_rawDescOnce.Do(func() {
		file_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_options_proto_rawDesc), len(file_options_proto_rawDesc)))
	})
	return file_options_proto_rawDescData
}

var file_options_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_options_proto_goTypes = []any{
	(*FieldOptions)(nil),                  // 0: protoc.gen.jsonschema.FieldOptions
	(*FileOptions)(nil),                   // 1: protoc.gen.jsonschema.FileOptions
	(*MessageOptions)(nil),                // 2: protoc.gen.jsonschema.MessageOptions
	(*EnumOptions)(nil),                   // 3: protoc.gen.jsonschema.EnumOptions
	(*EnumValueOptions)(nil),              // 4: protoc.gen.jsonschema.EnumValueOptions
	(*descriptorpb.FieldOptions)(nil),     // 5: google.protobuf.FieldOptions
	(*descriptorpb.FileOptions)(nil),      // 6: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil),   // 7: google.protobuf.MessageOptions
	(*descriptorpb.EnumOptions)(nil),      // 8: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 9: google.protobuf.EnumValueOptions
}
var file_options_proto_depIdxs = []int32{
	5,  // 0: protoc.gen.jsonschema.field_options:extendee -> google.protobuf.FieldOptions
	6,  // 1: protoc.gen.jsonschema.file_options:extendee -> google.protobuf.FileOptions
	7,  // 2: protoc.gen.jsonschema.message_options:extendee -> google.protobuf.MessageOptions
	8,  // 3: protoc.gen.jsonschema.enum_options:extendee -> google.protobuf.EnumOptions
	9,  // 4: protoc.gen.jsonschema.enum_value_options:extendee -> google.protobuf.EnumValueOptions
	0,  // 5: protoc.gen.jsonschema.field_options:type_name -> protoc.gen.jsonschema.FieldOptions
	1,  // 6: protoc.gen.jsonschema.file_options:type_name -> protoc.gen.jsonschema.FileOptions
	2,  // 7: protoc.gen.jsonschema.message_options:type_name -> protoc.gen.jsonschema.MessageOptions
	3,  // 8: protoc.gen.jsonschema.enum_options:type_name -> protoc.gen.jsonschema.EnumOptions
	4,  // 9: protoc.gen.jsonschema.enum_value_options:type_name -> protoc.gen.jsonschema.EnumValueOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	5,  // [5:10] is the sub-list for extension type_name
	0,  // [0:5] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_options_proto_init() }
func file_options_proto_init() {
	if File_options_proto != nil {
		return
	}
	file_options_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_proto_rawDesc), len(file_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_options_proto_goTypes,
		DependencyIndexes: file_options_proto_depIdxs,
		MessageInfos:      file_options_proto_msgTypes,
		ExtensionInfos:    file_options_proto_extTypes,
	}.Build()
	File_options_proto = out.File
	file_options_proto_goTypes = nil
	file_options_proto_depIdxs = nil
}
